print("int() bare kutter desimalene, uansett hvor stor eller liten desimaldelen er:")
print("int(2.25) er", int(2.25))
print("int(2.5) er", int(2.5))
print("int(2.99) er", int(2.99))
print("round() runder av til nærmeste heltall, f.eks.")
print("round(2.25) er", round(2.25))
print("round(2.51) er", round(2.51))
print("Hva hvis tallet er midt mellom to heltall?")
print("round(2.5) er", round(2.5))
print("round(3.5) er", round(3.5))
print("round() bruker en IEEE standard som velger partallet for midt-imellom-situasjoner.")
print("Mens int() alltid gir heltall kan round() brukes for antall desimaler:")
print("round(2.5488, 1) blir", round(2.5488, 1))
print("round(2.5488, 3) blir", round(2.5488, 3))
print("Med negativt antall desimaler kan vi få round() til å runde større enn heltall:")
print("round(12345.67, -3) blir", round(12345.67, -3)